banner:
    charset: UTF-8
    location: classpath:banner.txt
spring:
    application:
        name: delivery-system

    datasource:
        driverClassName: org.postgresql.Driver
#        url: jdbc:postgresql://83.69.129.245:5432/delivery-system
        url: jdbc:postgresql://89.208.229.186/delivery-system
        username: deliveryIsystem
        password: 097eYh&e4i20H4KY
        sql-script-encoding: UTF-8

    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

    jackson:
        serialization:
        INDENT_OUTPUT: true
        date-format: HH:mm dd/MM/yyyy
        time-zone: Asia/Tashkent

    http:
        multipart:
          max-file-size: 128KB
          max-request-size: 128KB
jwt:
    header: Authorization
    secret: $sudoco$2017_delivery_system/build*our\team&in^2017
    expiration: 360000000
    baseApiPath: /api/v1

route:
    authentication:
        shop: /shop/auth
        deliver: /deliver/auth
        owner: /owner/auth
        firm: /firm/auth
        refresh: refresh
    logout: logout

server:
    port: 8080