package uz.delivery_system.entity.base;

import uz.delivery_system.utils.CommonUtils;

import javax.persistence.*;
import java.io.Serializable;


@MappedSuperclass
public abstract class BaseEntity implements Serializable {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getId() == null) {
            return false;
        }
        if (getId().equals(((BaseEntity) obj).getId())) {
            return true;
        }
        return false;
    }

    @Override
    public String toString() {
        return "[id=" + getId() + "]";
    }

    public boolean isNew() {
        if (CommonUtils.isNotNull(getId())) {
            return false;
        }
        return true;
    }
}